### ISSUE TITLE
Keyboard Nav does strange things

### ISSUE THREAD

**Issue by 4yre** [F1F7Y/Better.Serverbrowser#7] opened 2021-12-28 21:37 UTC
1)
Just open the server browser and press arrow up (or down) till you reach either end of the list, then press the same arrow key again (maybe more than once) as if you wanted to navigate further in the same direction.
It will connect you to a server (I'm pretty sure its the one at the end of the list I navigated to).

2)
Its not possible to navigate the filter settings using the keyboard.
Also if any of the filter settings fields has focus and you do use the arrow keys it scrolls the list.
I think that could be fixed by check if any server list element has focus and only if so reacting to keyboard input by scrolling.

**Comment by F1F7Y** [comment] 2021-12-28 21:42
1. Am aware of that and know the cause, should be fixed in next release
2. Not all elements are currently setup for arrow navigation.

**Comment by 4yre** [comment] 2021-12-28 21:44
2 was more about the part that it scrolls even so that the filter settings element has focus, not the keyboard nav for the settings not working

**Closed as completed** 2021-12-29 15:40 UTC
